name: Assignment 01

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:  

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: echo "No dependencies to install"

      - name: Run lint
        run: echo "Linting passed"

      - name: Run tests
        run: echo "All tests passed"

      - name: Save build artifact
        run: |
          mkdir -p artifact
          echo "Build output or test report" > artifact/report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ github.run_id }
          path: artifact/

  deploy_qa:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/dev'
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Deploy to QA
        run: echo "Deploying to QA with artifact"

  deploy_prod:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Deploy to Production
        run: echo "Deploying to Production with artifact"

      - name: Send Slack notification
        run: echo "Notify team about Production deploy"
